name: Release iOS Demo App

on:
  push:
    branches:
      - main
    paths:
      - VERSION

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  build-ipa:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Build IPA
        uses: ./.github/actions/build-ipa
        with:
          certificate_p12_base64: ${{ secrets.MPARTICLE_ENTERPRISE_CERTIFICATE_P12_BASE64 }}
          certificate_password: ${{ secrets.MPARTICLE_ENTERPRISE_CERTIFICATE_PASSPHRASE }}
          provisioning_profile_base64: ${{ secrets.MPARTICLE_ENTERPRISE_PROVISIONING_PROFILE_BASE64 }}

  release-to-firebase-and-tag:
    runs-on: macos-15
    needs: build-ipa

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Download IPA artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: release-ipa
          path: .

      - name: Get version info
        id: version-info
        run: |
          # Extract version name (CFBundleShortVersionString) and build number (CFBundleVersion) from Info.plist
          VERSION_NAME=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" RoktDemo/Info.plist)
          BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" RoktDemo/Info.plist)

          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Get release notes
        id: release-notes
        run: |
          # Get the commit message of the last merge
          RELEASE_NOTES=$(git log -1 --pretty=%B)
          # Escape newlines and quotes for JSON
          RELEASE_NOTES=$(echo "$RELEASE_NOTES" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT

      - name: Upload IPA to Firebase
        uses: ./.github/actions/upload-ipa
        with:
          ipa_path: RoktDemo.ipa
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          firebase_app_id: ${{ secrets.FIREBASE_APP_ID }}
          testing_groups: ${{ secrets.TESTING_GROUPS }}
          release_notes: ${{ steps.release-notes.outputs.release_notes }}

      - name: Create GitHub release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          artifacts: RoktDemo.ipa
          makeLatest: true
          tag: ${{ steps.version-info.outputs.version_name }}
          body: |
            ## Release notes:
            ${{ steps.release-notes.outputs.release_notes }}
    