name: Release from main

on:
  push:
    branches:
      - main
    paths:
      - VERSION

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get current version
        id: version-file
        run: |
          version_from_file=$(head -n 1 VERSION)
          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT

      - name: Get changelog content
        id: get-changelog
        uses: ffurrer2/extract-release-notes@cae32133495112d23e3569ad04fef240ba4e7bc8 # v2.3.0
        with:
          changelog_file: CHANGELOG.md

      - name: Setup keychain and import certificate
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          echo "${{ secrets.MPARTICLE_ENTERPRISE_CERTIFICATE_P12_BASE64 }}" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "${{ secrets.MPARTICLE_ENTERPRISE_CERTIFICATE_PASSPHRASE }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.MPARTICLE_ENTERPRISE_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - run: pod install

      - name: Archive the app
        run: |
          xcodebuild -workspace RoktDemo.xcworkspace \
            -scheme RoktDemo \
            -configuration Release \
            -archivePath build/RoktDemo.xcarchive \
            archive | xcpretty

      - name: Export the app
        run: |
          xcodebuild -exportArchive \
            -archivePath build/RoktDemo.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build | xcpretty

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          tag_name: ${{ steps.version-file.outputs.release-version }}
          name: Release ${{ steps.version-file.outputs.release-version }}
          make_latest: true
          body: |
            Release ${{ steps.version-file.outputs.release-version }}
            ## Release notes:
            ${{ steps.get-changelog.outputs.release_notes }}