name: Release from main

on:
  push:
    branches:
      - main
    paths:
      - VERSION

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get current version
        id: version-file
        run: |
          version_from_file=$(head -n 1 VERSION)
          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT

      - name: Get changelog content
        id: get-changelog
        uses: ffurrer2/extract-release-notes@cae32133495112d23e3569ad04fef240ba4e7bc8 # v2.3.0
        with:
          changelog_file: CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          tag_name: ${{ steps.version-file.outputs.release-version }}
          name: Release ${{ steps.version-file.outputs.release-version }}
          make_latest: true
          body: |
            Release ${{ steps.version-file.outputs.release-version }}
            ## Release notes:
            ${{ steps.get-changelog.outputs.release_notes }}